providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "18"
NODE_ENV = "production"

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
